### ISSUE TITLE
Tap fails with TypeError: 'NoneType' object is not iterable when iterating over raw_metadata

### ISSUE THREAD

**Issue by allanw** [fishtown-analytics/tap-trustpilot#1]
I installed tap-trustpilot and generated a `catalog.json` file by doing `tap-trustpilot -c config.json --discover > catalog.json`

When I try and run the tap using `tap-trustpilot -c config.json -p catalog.json`, I get the following error:

```
CRITICAL 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/bin/tap-trustpilot", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/singer/utils.py", line 229, in wrapped
    return fnc(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tap_trustpilot/__init__.py", line 75, in main
    if args.properties else discover(ctx)
  File "/usr/local/lib/python3.7/site-packages/tap_trustpilot/context.py", line 36, in catalog
    [s.tap_stream_id for s in catalog.streams
  File "/usr/local/lib/python3.7/site-packages/tap_trustpilot/context.py", line 37, in <listcomp>
    if s.is_selected()]
  File "/usr/local/lib/python3.7/site-packages/singer/catalog.py", line 48, in is_selected
    mdata = metadata_module.to_map(self.metadata)
  File "/usr/local/lib/python3.7/site-packages/singer/metadata.py", line 5, in to_map
    return {tuple(md['breadcrumb']): md['metadata'] for md in raw_metadata}
TypeError: 'NoneType' object is not iterable
```

This error originates from singer itself in the `catalog.py` file:

```
    def is_selected(self):
        mdata = metadata_module.to_map(self.metadata)
```

Any help would be appreciated!

**Comment by drewbanin** [comment]
Hey @allanw - it's been a pretty long time since I've looked at this repo!

I think there are a couple of things to sort out here:
 - the `singer-python` dep is set to `singer-python>=5.0.12`, but it should probably have an upper bound on `5.2.0`.
 - the `pendulum` package should be added to `setup.py`

If you make both of those changes, this should at least... run. I don't have credentials handy for a TrustPilot account anymore, so I'm afraid I can't test this out any further than that! Let me know if you hit any other snags.

**Comment by allanw** [comment]
Hey @drewbanin, thanks for your reply - I upgraded the version of `singer-python` and it's up and running now 👍
